version: '3.7'

services:
  app:
    image: bulker-django-backend
    volumes:
      - .:/code
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DJANGO_DEBUG=False
    env_file:
      - .env
      - django.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  mongodb:
    image: mongo:5.0.6
    volumes:
      - ./data/db:/var/lib/mongodb/data
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
      - mongo.env