version: '3.7'

services:
  app:
    image: bulker-django-backend
    volumes:
      - .:/code
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DJANGO_DEBUG=True
    env_file:
      - .env
      - django.env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python manage.py migrate && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678

  mongodb:
    image: mongo:5.0.6
    volumes:
      - ./data/db:/var/lib/mongodb/data
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
      - mongo.env