version: '3.7'

services:
  app:
    image: bulker
    volumes:
      - .:/code
    depends_on:
      - mongodb
    environment:
      - DB_NAME=db-bulker
      - DB_HOST=mongodb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pswd1234
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY='@s(eis)_8ssp#ua4%0pmdc4%$vsj13nn*_r+_2*fxd!jxi0#'
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python manage.py migrate && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678

  mongodb:
    image: mongo:5.0.6
    volumes:
    - ./data/db:/var/lib/mongodb/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pswd1234