version: '3.7'

services:
  bulker:
    image: bulker-django-backend
    volumes:
      - static_volume:/bulker-django-backend/static
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DJANGO_DEBUG=False
    env_file:
      - .env
      - django.env
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - db_network
      - nginx_network

  mongodb:
    image: mongo:5.0.6
    volumes:
      - ./data/db:/var/lib/mongodb/data
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
      - mongo.env
    networks:
      - db_network

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
      - static_volume:/bulker-django-backend/static
    ports:
      - 8080:80
    depends_on:
      - bulker
    networks:
      - nginx_network

volumes:
  static_volume:

networks:
  nginx_network:
    driver: bridge

  db_network:
    driver: bridge