apiVersion: v1
kind: Secret
metadata:
  name: appsecrets
data:
  db-user: {{ .Values.db_user | b64enc }}
  db-name: {{ .Values.db_name | b64enc }}
  db-password: {{ .Values.db_password | b64enc }}
  db-host: {{ .Values.db_host | b64enc }}
  db-port: {{ .Values.db_port | b64enc }}
  host: {{ .Values.host | b64enc }}
  secret-key: {{ .Values.secret_key | b64enc }}