# Generated by Django 4.0.2 on 2022-02-05 09:00

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_age_alter_player_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=players.models.Player.generate_age, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=players.models.Player.generate_gender, max_length=1, verbose_name='Gender'),
        ),
    ]
