name: Django CI Workflow

# Triggers that workflow on such occasions, as pull request/push to master/develop
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  code-style-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check Python version
        run: python --version
      - name: Install and use Pycodestyle
        run: |
          python -m pip install pycodestyle==2.8.0
          pycodestyle --statistics .

  health-check-job:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ['3.9', '3.10'] # Run job for both Python 3.9 and 3.10
    services:
      mongodb:
        image: mongo:5.0.6
        env:
          MONGO_INITDB_ROOT_USERNAME: mongoadmin
          MONGO_INITDB_ROOT_PASSWORD: Password-To-Pass
        ports:
          - 27017:27017
    steps:
      - name: Checkout code       # Pulling a project commit that triggered the workflow
        uses: actions/checkout@v2
      - name: Cache dependency    # Create cache for project dependencies to improve performance
        uses: actions/cache@v2
        with:
          path: ~/.cache/~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Check Python version
        run: python --version
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Configure '.env' file
        run: |
          echo -e "MONGO_INITDB_ROOT_USERNAME=mongoadmin\nMONGO_INITDB_ROOT_PASSWORD=Password-To-Pass" > .env
          python confenv.py False
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test